// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExtractCoverImage(arg1) {
  return window['go']['main']['App']['ExtractCoverImage'](arg1);
}

export function ExtractPage(arg1) {
  return window['go']['main']['App']['ExtractPage'](arg1);
}

export function GetPage(arg1, arg2) {
  return window['go']['main']['App']['GetPage'](arg1, arg2);
}

export function OpenComic(arg1) {
  return window['go']['main']['App']['OpenComic'](arg1);
}

export function ScanDirectory(arg1) {
  return window['go']['main']['App']['ScanDirectory'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}
