// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {zip} from '../models';
import {main} from '../models';

export function ExtractCoverImage(arg1:string):Promise<string>;

export function ExtractPage(arg1:zip.File):Promise<string>;

export function GetPage(arg1:string,arg2:number):Promise<main.ComicPage>;

export function OpenComic(arg1:string):Promise<Record<string, any>>;

export function ScanDirectory(arg1:string):Promise<Array<main.Comic>>;

export function SelectDirectory():Promise<string>;
